<?php
return array(
    array("cognome"=>"Toscani","nome"=>"Santina","res_luogo"=>"Sali Vercellese","res_cap"=>"13040","indirizzo"=>"Vicolo S.Babila, 182","telefono"=>"0161/1006594","email"=>"santina.toscani@tele2.it"),
    array("cognome"=>"Tasconi","nome"=>"Miranda","res_luogo"=>"Fanano","res_cap"=>"41021","indirizzo"=>"Via Rho, 8/c","telefono"=>"059/1033741","email"=>"miranda.tasconi@teletu.it"),
    array("cognome"=>"Prestagiacomo","nome"=>"Fabiola","res_luogo"=>"San Martino Buon Albergo","res_cap"=>"37036","indirizzo"=>"Passaggio B.Gravina, 260","telefono"=>"045/114925","email"=>"fabi.pres@aruba.it"),
    array("cognome"=>"Monachini","nome"=>"Renzo","res_luogo"=>"Montjuvet","res_cap"=>"11020","indirizzo"=>"Piazzale S.Regione, 243/c","telefono"=>"0165/627700","email"=>"renz.mona@yahoo.it"),
    array("cognome"=>"Gandini","nome"=>"Pia","res_luogo"=>"Cortale","res_cap"=>"88020","indirizzo"=>"Via V.Betteloni, 101","telefono"=>"0961/1041104","email"=>"pia.gandini@gmail.com"),
    array("cognome"=>"Bertoncini","nome"=>"Diogene","res_luogo"=>"Cimego","res_cap"=>"38082","indirizzo"=>"Via G.Serbelloni, 228","telefono"=>"0461/237246","email"=>"diogene.bertoncini@libero.it"),
    array("cognome"=>"Molinari","nome"=>"Gustavo","res_luogo"=>"Sessano del Molise","res_cap"=>"86090","indirizzo"=>"Via Benefattori dell'Ospedale, 203","telefono"=>"0865/923578","email"=>"gustavo.molinari@tele2.it"),
    array("cognome"=>"Milo","nome"=>"Moreno","res_luogo"=>"Carapelle Calvisio","res_cap"=>"67020","indirizzo"=>"Via Val Badia, 237","telefono"=>"0862/596662","email"=>"moreno.milo@teletu.it"),
    array("cognome"=>"Balbini","nome"=>"Zaccheo","res_luogo"=>"Zelbio","res_cap"=>"22020","indirizzo"=>"Via S.Arialdo, 103","telefono"=>"031/472962","email"=>"zaccheo.balbini@lycos.it"),
    array("cognome"=>"Terranova","nome"=>"Damiano","res_luogo"=>"Copiano","res_cap"=>"27010","indirizzo"=>"Via L.Pulci, 206","telefono"=>"0382/880379","email"=>"dami.terr@teletu.it"),
    array("cognome"=>"Freddi","nome"=>"Brunilde","res_luogo"=>"Cerchiara di Calabria","res_cap"=>"87070","indirizzo"=>"Via A.Panzini, 286","telefono"=>"0984/943316","email"=>"brunilde.freddi@aruba.it"),
    array("cognome"=>"Gargi","nome"=>"Rossella","res_luogo"=>"Vallelunga Pratameno","res_cap"=>"93010","indirizzo"=>"Via D.Comboni, 148","telefono"=>"0934/1004272","email"=>"rossella.gargi@gmail.com"),
    array("cognome"=>"Brancaleone","nome"=>"Salomone","res_luogo"=>"San Chirico Raparo","res_cap"=>"85030","indirizzo"=>"Via G.D'Annunzio, 17","telefono"=>"0971/556687","email"=>"salo.bran@gmail.it"),
    array("cognome"=>"Positano","nome"=>"Emma","res_luogo"=>"Rivanazzano","res_cap"=>"27055","indirizzo"=>"Via D.Albertario, 209/c","telefono"=>"0382/1011903","email"=>"emma.positano@virgilio.it"),
    array("cognome"=>"Boglia","nome"=>"Bortolo","res_luogo"=>"Pellezzano","res_cap"=>"84080","indirizzo"=>"Via S.Mazzucchelli, 95","telefono"=>"089/1021182","email"=>"bortolo.boglia@tiscali.it"),
    array("cognome"=>"Manes","nome"=>"Aimone","res_luogo"=>"Villamarzana","res_cap"=>"45030","indirizzo"=>"Corso A.Beretta, 190/b","telefono"=>"0425/290558","email"=>"aimone.manes@yahoo.com"),
    array("cognome"=>"Paolucci","nome"=>"Abele","res_luogo"=>"Rolo","res_cap"=>"42047","indirizzo"=>"Via Mottarone, 138/c","telefono"=>"0522/177449","email"=>"abele.paolucci@aruba.it"),
    array("cognome"=>"Piuma","nome"=>"Edgardo","res_luogo"=>"Sluderno","res_cap"=>"39020","indirizzo"=>"Via N.Armorari, 13","telefono"=>"0471/1035970","email"=>"edgardo.piuma@teletu.it"),
    array("cognome"=>"Carugati","nome"=>"Lapo","res_luogo"=>"Zanica","res_cap"=>"24050","indirizzo"=>"Via C.Cazzaniga, 1","telefono"=>"035/732806","email"=>"lapo.carugati@katamail.it"),
    array("cognome"=>"Castagnaro","nome"=>"Rodrigo","res_luogo"=>"Isole Tremiti","res_cap"=>"71040","indirizzo"=>"Via Piacenza, 111","telefono"=>"0881/871694","email"=>"rodrigo.castagnaro@libero.it"),
    array("cognome"=>"Cornaro","nome"=>"Ciro","res_luogo"=>"Bagno a Ripoli","res_cap"=>"50012","indirizzo"=>"Via G.Sapeto, 158/e","telefono"=>"055/223194","email"=>"ciro.cornaro@aruba.it"),
    array("cognome"=>"Piantanida","nome"=>"Annagrazia","res_luogo"=>"Valderice","res_cap"=>"91019","indirizzo"=>"Via Valle Aurina, 96","telefono"=>"0923/375179","email"=>"annagrazia.piantanida@gmail.com"),
    array("cognome"=>"Barili","nome"=>"Beato","res_luogo"=>"Colazza","res_cap"=>"28010","indirizzo"=>"Via B.Spinoza, 117","telefono"=>"0321/394207","email"=>"beato.barili@tin.it"),
    array("cognome"=>"Marucchi","nome"=>"Bartolomeo","res_luogo"=>"Tirolo","res_cap"=>"39019","indirizzo"=>"Via Stelline, 192","telefono"=>"0471/514651","email"=>"bartolomeo.marucchi@yahoo.com"),
    array("cognome"=>"Monaci","nome"=>"Beniamina","res_luogo"=>"Arsiero","res_cap"=>"36011","indirizzo"=>"Via P.Valery, 173","telefono"=>"0444/217839","email"=>"b.monaci@gmail.it"),
    array("cognome"=>"De Ciancio","nome"=>"Attila","res_luogo"=>"Passerano Marmorito","res_cap"=>"14020","indirizzo"=>"Via G.Bardelli, 237","telefono"=>"0141/184197","email"=>"attila.deciancio@tiscali.it"),
    array("cognome"=>"Perro","nome"=>"Loreno","res_luogo"=>"Misilmeri","res_cap"=>"90036","indirizzo"=>"Via G.Adria, 161","telefono"=>"091/869239","email"=>"loreno.perro@teletu.it"),
    array("cognome"=>"Paladino","nome"=>"Decimo","res_luogo"=>"San Pellegrino Terme","res_cap"=>"24016","indirizzo"=>"Via Privata P.Acerenza, 226","telefono"=>"0345/1043480","email"=>"decimo.paladino@gmail.com"),
    array("cognome"=>"Brau","nome"=>"Elsa","res_luogo"=>"Porte","res_cap"=>"10060","indirizzo"=>"Via F.T.Marinetti, 267","telefono"=>"011/856533","email"=>"elsa.brau@tin.it"),
    array("cognome"=>"Goffi","nome"=>"Anna","res_luogo"=>"Leporano","res_cap"=>"74020","indirizzo"=>"Via A.Funi, 16","telefono"=>"099/958188","email"=>"anna.goffi@teletu.it"),
    array("cognome"=>"Camana","nome"=>"Nazzareno","res_luogo"=>"Levanto","res_cap"=>"19015","indirizzo"=>"Cavalcavia Mafalda di Savoia, 19","telefono"=>"0187/186286","email"=>"nazzareno.camana@gmail.com"),
    array("cognome"=>"Martorelli","nome"=>"Virginia","res_luogo"=>"Ronco Briantino","res_cap"=>"20050","indirizzo"=>"Via E.Bugatti, 269","telefono"=>"02/384822","email"=>"virginia.martorelli@gmail.it"),
    array("cognome"=>"Camnasio","nome"=>"Fulvia","res_luogo"=>"Cavaglià","res_cap"=>"13042","indirizzo"=>"Via Castagnevizza, 255","telefono"=>"0161/863820","email"=>"fulvia.camnasio@teletu.it"),
    array("cognome"=>"Boiocchi","nome"=>"Natale","res_luogo"=>"Calvi Risorta","res_cap"=>"81042","indirizzo"=>"Via J.V.Dal Verme, 244","telefono"=>"0823/918371","email"=>"nata.boio@tiscali.it"),
    array("cognome"=>"Robbiati","nome"=>"Gianpiero","res_luogo"=>"Grottolella","res_cap"=>"83010","indirizzo"=>"Piazzale S.Maria Podone, 241","telefono"=>"0825/815761","email"=>"g.robbiati@tiscali.it"),
    array("cognome"=>"Duce","nome"=>"Socrate","res_luogo"=>"Villagrande Strisaili","res_cap"=>"08049","indirizzo"=>"Via M.Bagni, 156","telefono"=>"0784/394822","email"=>"socrate.duce@lycos.it"),
    array("cognome"=>"Salmistraro","nome"=>"Bernadetta","res_luogo"=>"Candiana","res_cap"=>"35020","indirizzo"=>"Via F.Barbieri, 260","telefono"=>"049/634443","email"=>"bernadetta.salmistraro@gmail.it"),
    array("cognome"=>"Calderara","nome"=>"Ercole","res_luogo"=>"Pollina","res_cap"=>"90010","indirizzo"=>"Via E.Noe, 111","telefono"=>"091/705510","email"=>"ercole.calderara@gmail.com"),
    array("cognome"=>"Polini","nome"=>"Amintore","res_luogo"=>"Neviano degli Arduini","res_cap"=>"43024","indirizzo"=>"Via Bellagio, 154","telefono"=>"0521/350840","email"=>"amin.poli@aruba.it"),
    array("cognome"=>"Mattiussi","nome"=>"Geltrude","res_luogo"=>"Rosasco","res_cap"=>"27030","indirizzo"=>"Corso V.Riolo, 31","telefono"=>"0382/988431","email"=>"geltrude.mattiussi@tiscali.it"),
    array("cognome"=>"Neiviller","nome"=>"Renzo","res_luogo"=>"Fiordimonte","res_cap"=>"62030","indirizzo"=>"Via Gaeta, 44/d","telefono"=>"0733/1017321","email"=>"renzo.neiviller@gmail.it"),
    array("cognome"=>"Orso","nome"=>"Maddalena","res_luogo"=>"Tornolo","res_cap"=>"43059","indirizzo"=>"Via Privata Broletto, 232","telefono"=>"0521/354525","email"=>"m.orso@gmail.com"),
    array("cognome"=>"Angeletti","nome"=>"Monica","res_luogo"=>"Fiesole","res_cap"=>"50014","indirizzo"=>"Via G.Bivona, 135","telefono"=>"055/487407","email"=>"monica.angeletti@gmail.com"),
    array("cognome"=>"Caponnetto","nome"=>"Annamaria","res_luogo"=>"Massa Carrara","res_cap"=>"54100","indirizzo"=>"Via P.Borghese detto Piero della Francesca, 237","telefono"=>"0585/948425","email"=>"anna.capo@libero.it"),
    array("cognome"=>"Stragazzi","nome"=>"Tibaldo","res_luogo"=>"Bomporto","res_cap"=>"41030","indirizzo"=>"Via G.Beato, 285","telefono"=>"059/747455","email"=>"tstragazzi@yahoo.com"),
    array("cognome"=>"Chinati","nome"=>"Beniamino","res_luogo"=>"Cabiate","res_cap"=>"22060","indirizzo"=>"Via L.Barba, 227","telefono"=>"031/286036","email"=>"b.chinati@teletu.it"),
    array("cognome"=>"Cirrincione","nome"=>"Vinicio","res_luogo"=>"Sanza","res_cap"=>"84030","indirizzo"=>"Via V.Salvagnoli, 12","telefono"=>"089/352120","email"=>"vinicio.cirrincione@aruba.it"),
    array("cognome"=>"Caratti","nome"=>"Beronico","res_luogo"=>"Fara Filiorum Petri","res_cap"=>"66010","indirizzo"=>"Via Fratelli Bazzaro, 60","telefono"=>"0871/519612","email"=>"beronico.caratti@virgilio.it"),
    array("cognome"=>"Gaballo","nome"=>"Linda","res_luogo"=>"Solofra","res_cap"=>"83029","indirizzo"=>"Via L.Adorno, 198/c","telefono"=>"0825/602279","email"=>"lind.gaba@tin.it"),
    array("cognome"=>"Grigoli","nome"=>"Placido","res_luogo"=>"Torri in Sabina","res_cap"=>"02049","indirizzo"=>"Via M.Polo, 261","telefono"=>"0746/971724","email"=>"placido.grigoli@libero.it"),
    array("cognome"=>"Sanguinetti","nome"=>"Dora","res_luogo"=>"Caselle Lurani","res_cap"=>"20080","indirizzo"=>"Via Peschiera, 77","telefono"=>"02/858261","email"=>"dora.sanguinetti@teletu.it"),
    array("cognome"=>"Bindi","nome"=>"Maffeo","res_luogo"=>"Naso","res_cap"=>"98074","indirizzo"=>"Via Durazzo, 22","telefono"=>"090/1050523","email"=>"maff.bind@tele2.it"),
    array("cognome"=>"Formica","nome"=>"Matilde","res_luogo"=>"Bastia","res_cap"=>"32010","indirizzo"=>"Via Lega Lombarda, 25","telefono"=>"075/375823","email"=>"matilde.formica@gmail.it"),
    array("cognome"=>"Carusio","nome"=>"Francesca","res_luogo"=>"Roncobello","res_cap"=>"24010","indirizzo"=>"Via A.De Gasperi, 113","telefono"=>"035/310088","email"=>"francesca.carusio@lycos.it"),
    array("cognome"=>"Distinzieri","nome"=>"Filippo","res_luogo"=>"Volano","res_cap"=>"38060","indirizzo"=>"Via S.Benfratello, 79","telefono"=>"0461/178314","email"=>"filippo.distinzieri@virgilio.it"),
    array("cognome"=>"Filippini","nome"=>"Aurelia","res_luogo"=>"Sassofeltrio","res_cap"=>"61010","indirizzo"=>"Via F.Franchi, 277/k","telefono"=>"0721/233893","email"=>"aure.fili@tiscali.it"),
    array("cognome"=>"Agreste","nome"=>"Dalila","res_luogo"=>"Villar San Costanzo","res_cap"=>"12020","indirizzo"=>"Via P.Perricone, 70/b","telefono"=>"0173/825153","email"=>"d.agreste@tele2.it"),
    array("cognome"=>"Degennaro","nome"=>"Nilde","res_luogo"=>"Ruoti","res_cap"=>"85056","indirizzo"=>"Via Nomis di Cossilla, 42","telefono"=>"0971/513907","email"=>"nilde.degennaro@aruba.it"),
    array("cognome"=>"Santus","nome"=>"Priscilla","res_luogo"=>"Larciano","res_cap"=>"51036","indirizzo"=>"Via Fontanafredda, 140","telefono"=>"0573/728328","email"=>"priscilla.santus@gmail.it"),
    array("cognome"=>"Zoccolanti","nome"=>"Reginaldo","res_luogo"=>"Vicopisano","res_cap"=>"56010","indirizzo"=>"Via G.Nicolosi, 223","telefono"=>"050/596949","email"=>"reginaldo.zoccolanti@gmail.it"),
    array("cognome"=>"Vasconi","nome"=>"Bice","res_luogo"=>"Carvico","res_cap"=>"24030","indirizzo"=>"Piazzale L.Galvani, 81","telefono"=>"035/932879","email"=>"bice.vasconi@tele2.it"),
    array("cognome"=>"Franzoso","nome"=>"Pierluigi","res_luogo"=>"Felonica","res_cap"=>"46022","indirizzo"=>"Via Bagutta, 103","telefono"=>"0376/560537","email"=>"pierluigi.franzoso@hotmail.com"),
    array("cognome"=>"Barboni","nome"=>"Terenzio","res_luogo"=>"Pedara","res_cap"=>"95030","indirizzo"=>"Via S.Arialdo, 171","telefono"=>"095/880984","email"=>"terenzio.barboni@gmail.it"),
    array("cognome"=>"Bussolotto","nome"=>"Eulalia","res_luogo"=>"Piverone","res_cap"=>"10010","indirizzo"=>"Via Miramare, 251/d","telefono"=>"011/167189","email"=>"eulalia.bussolotto@tiscali.it"),
    array("cognome"=>"Tassistro","nome"=>"Renata","res_luogo"=>"Motteggiana","res_cap"=>"46020","indirizzo"=>"Via G.Arrivabene, 216","telefono"=>"0376/690758","email"=>"renata.tassistro@gmail.it"),
    array("cognome"=>"Munaretti","nome"=>"Evelina","res_luogo"=>"Belvedere Langhe","res_cap"=>"12060","indirizzo"=>"Via A.Ripellino, 54","telefono"=>"0173/510860","email"=>"evelina.munaretti@tele2.it"),
    array("cognome"=>"Libone","nome"=>"Guerrino","res_luogo"=>"San Mauro Castelverde","res_cap"=>"90010","indirizzo"=>"Via N.Candela, 278","telefono"=>"091/350228","email"=>"guer.libo@aruba.it"),
    array("cognome"=>"Califano","nome"=>"Genoveffa","res_luogo"=>"Sossano","res_cap"=>"36040","indirizzo"=>"Via dei Carabinieri d'Italia, 13","telefono"=>"0444/485805","email"=>"geno.cali@hotmail.com"),
    array("cognome"=>"Perosini","nome"=>"Primo","res_luogo"=>"Badalucco","res_cap"=>"18010","indirizzo"=>"Via M.Luther King, 228","telefono"=>"0183/1007826","email"=>"primo.perosini@lycos.it"),
    array("cognome"=>"Tiezzi","nome"=>"Lino","res_luogo"=>"Arola","res_cap"=>"28010","indirizzo"=>"Via Trenno, 180","telefono"=>"0321/1072311","email"=>"lino.tiez@gmail.com"),
    array("cognome"=>"Iacopino","nome"=>"Alcide","res_luogo"=>"Fiumefreddo di Sicilia","res_cap"=>"95013","indirizzo"=>"Via Agamennone, 100","telefono"=>"095/535891","email"=>"alci.iaco@yahoo.it"),
    array("cognome"=>"Calledda","nome"=>"Cinzia","res_luogo"=>"Serdiana","res_cap"=>"09040","indirizzo"=>"Via S.Bernardino, 30","telefono"=>"070/453592","email"=>"cinzia.calledda@hotmail.com"),
    array("cognome"=>"Lanaro","nome"=>"Gaia","res_luogo"=>"Carvico","res_cap"=>"24030","indirizzo"=>"Via Settimio Severo, 34","telefono"=>"035/150869","email"=>"gaia.lana@virgilio.it"),
    array("cognome"=>"Stigliani","nome"=>"Aurelio","res_luogo"=>"Bocchigliero","res_cap"=>"87060","indirizzo"=>"Cavalcavia G.Maielli, 282/h","telefono"=>"0984/623499","email"=>"aurelio.stigliani@gmail.com"),
    array("cognome"=>"Zoratti","nome"=>"Viola","res_luogo"=>"Comezzano-Cizzago","res_cap"=>"25030","indirizzo"=>"Largo Fiume Sangro, 101","telefono"=>"030/736175","email"=>"viol.zora@gmail.com"),
    array("cognome"=>"Saccaro","nome"=>"Serafino","res_luogo"=>"Martinsicuro","res_cap"=>"64014","indirizzo"=>"Via F.Donzelli, 120/h","telefono"=>"0861/527664","email"=>"sera.sacc@virgilio.it"),
    array("cognome"=>"Tona","nome"=>"Cornelia","res_luogo"=>"San Pietro di Feletto","res_cap"=>"31020","indirizzo"=>"Via Marco Bruto, 140","telefono"=>"0422/366063","email"=>"cornelia.tona@gmail.com"),
    array("cognome"=>"Ramaglia","nome"=>"Girolamo","res_luogo"=>"Varzi","res_cap"=>"27057","indirizzo"=>"Via Virgilio, 221/d","telefono"=>"0382/162188","email"=>"giro.rama@virgilio.it"),
    array("cognome"=>"Ciccardini","nome"=>"Napoleone","res_luogo"=>"Zone","res_cap"=>"25050","indirizzo"=>"Via G.B.Brocchi, 77/i","telefono"=>"030/524916","email"=>"napoleone.ciccardini@lycos.it"),
    array("cognome"=>"Di Bartoli","nome"=>"Asia","res_luogo"=>"Fogliano Redipuglia","res_cap"=>"34070","indirizzo"=>"Via G.Pacini, 140","telefono"=>"0481/996392","email"=>"asia.diba@aruba.it"),
    array("cognome"=>"Bagnatica","nome"=>"Domenico","res_luogo"=>"Cavaria con Premezzo","res_cap"=>"21044","indirizzo"=>"Via A.Bonzagni, 281/b","telefono"=>"0332/899478","email"=>"dome.bagn@gmail.com"),
    array("cognome"=>"De Mattio","nome"=>"Luciana","res_luogo"=>"Poggio Berni","res_cap"=>"47030","indirizzo"=>"Via dei Liutai, 234/j","telefono"=>"0543/990282","email"=>"luciana.demattio@libero.it"),
    array("cognome"=>"Gallina","nome"=>"Cora","res_luogo"=>"Santo Stefano di Sessanio","res_cap"=>"67020","indirizzo"=>"Via G.Perego, 99","telefono"=>"0862/726731","email"=>"cora.gallina@gmail.com"),
    array("cognome"=>"Crisostomi","nome"=>"Ascanio","res_luogo"=>"Linarolo","res_cap"=>"27010","indirizzo"=>"Via Bene Vagienna, 229","telefono"=>"0382/304901","email"=>"ascanio.crisostomi@teletu.it"),
    array("cognome"=>"Marzocchi","nome"=>"Samuele","res_luogo"=>"Visano","res_cap"=>"25010","indirizzo"=>"Via San Francesco, 66","telefono"=>"030/374055","email"=>"samuele.marzocchi@lycos.it"),
    array("cognome"=>"Nisi","nome"=>"Ortensia","res_luogo"=>"Gallicano nel Lazio","res_cap"=>"00100","indirizzo"=>"Via F.Albini, 224","telefono"=>"06/740017","email"=>"ortensia.nisi@tiscali.it"),
    array("cognome"=>"Alamanno","nome"=>"Lamberto","res_luogo"=>"Cavallerleone","res_cap"=>"12030","indirizzo"=>"Via S.Fedele, 104","telefono"=>"0173/113958","email"=>"lamberto.alamanno@gmail.it"),
    array("cognome"=>"Ciutti","nome"=>"Damocle","res_luogo"=>"Castel San Vincenzo","res_cap"=>"86071","indirizzo"=>"Piazza Licurgo, 92","telefono"=>"0865/590608","email"=>"damo.ciut@tiscali.it"),
    array("cognome"=>"Brau","nome"=>"Giacobbe","res_luogo"=>"Ardauli","res_cap"=>"09081","indirizzo"=>"Via P.Corradini, 170/j","telefono"=>"0783/794875","email"=>"giacobbe.brau@gmail.it"),
    array("cognome"=>"Chinno","nome"=>"Simeone","res_luogo"=>"Reano","res_cap"=>"10090","indirizzo"=>"Via Doberdà, 295","telefono"=>"011/438224","email"=>"simeone.chinno@gmail.com"),
    array("cognome"=>"Zanchi","nome"=>"Glauco","res_luogo"=>"Varallo","res_cap"=>"13019","indirizzo"=>"Via G.Pini, 117","telefono"=>"0161/199407","email"=>"glauco.zanchi@tele2.it"),
    array("cognome"=>"Vilardo","nome"=>"Rino","res_luogo"=>"Piea","res_cap"=>"14020","indirizzo"=>"Vicolo E.Toti, 239","telefono"=>"0141/765723","email"=>"rino.vilardo@katamail.it"),
    array("cognome"=>"Cosentini","nome"=>"Ulisse","res_luogo"=>"Cermes","res_cap"=>"39010","indirizzo"=>"Via Vetra, 150","telefono"=>"0471/109053","email"=>"ulisse.cosentini@virgilio.it"),
    array("cognome"=>"Gaburri","nome"=>"Ludovico","res_luogo"=>"Nicorvo","res_cap"=>"27020","indirizzo"=>"Via Gelsomini, 120","telefono"=>"0382/248150","email"=>"ludovico.gaburri@virgilio.it"),
    array("cognome"=>"Sanesi","nome"=>"Sabina","res_luogo"=>"Frascineto","res_cap"=>"87010","indirizzo"=>"Via Negroli, 149","telefono"=>"0984/523214","email"=>"sabi.sane@tin.it"),
    array("cognome"=>"Venere","nome"=>"Walter","res_luogo"=>"Sovizzo","res_cap"=>"36050","indirizzo"=>"Piazzetta Garofani, 93","telefono"=>"0444/225091","email"=>"w.venere@yahoo.com"),
    array("cognome"=>"Baudini","nome"=>"Geltrude","res_luogo"=>"Carapelle","res_cap"=>"71041","indirizzo"=>"Via S.Meccio, 137","telefono"=>"0881/422936","email"=>"geltrude.baudini@tiscali.it"),
    array("cognome"=>"Depinè","nome"=>"Beatrice","res_luogo"=>"Lavagna","res_cap"=>"16033","indirizzo"=>"Via A.Del Castagno, 19","telefono"=>"010/673926","email"=>"beatrice.depin@gmail.com"),
    array("cognome"=>"Gatel","nome"=>"Orfeo","res_luogo"=>"Meda","res_cap"=>"20036","indirizzo"=>"Via L.Vitali, 17/d","telefono"=>"02/561297","email"=>"orfeo.gatel@tin.it"),
    array("cognome"=>"Guiglia","nome"=>"Marica","res_luogo"=>"Villa di Tirano","res_cap"=>"23030","indirizzo"=>"Via G.Pecori Giraldi, 190","telefono"=>"0342/105276","email"=>"marica.guiglia@teletu.it")
);
